series: C++ IO
title: Basic Console IO
author:
  name: David Erbelding
  email: daviderbelding@gmail.com
  github: https://github.com/Erbelding
description: A basic console application using string and iostream.
language: C++
tags:
  - Core
extra_resources:
connections: