series: Basic C++
title: Hello World!
author:
  name: David Erbelding
  email: daviderbelding@gmail.com
  github: https://github.com/Erbelding
description: This program is very excited to meet you.
language: C++
tags:
  - Core
extra_resources:
connections:
